### ISSUE TITLE
Users and Organizations in separate apps

### ISSUE THREAD

**Issue by apsideproj** [openwisp/openwisp-users#181]
Can this package support Users and Organizations being in separate apps? For example, I have Users in an app called "users" and I have Company in an app called "company". Will this package support that use case?

**Comment by nemesisdesign** [comment]
I think it's doable, by using it as a library and defining the models in two separate apps, read there: https://github.com/openwisp/openwisp-users#extend-openwisp-users.
I'm closing because it's not really and issue but more a support question. Feel free to keep asking questions if you need or create an issue if you find a problem while trying to implement what you need.

**Comment by apsideproj** [comment]
Hi @nemesisdesign .. I do have a follow up question. I decided to add my models in one single app. However, I created a directory for `models` a new file for each model just for better readability and structure. When I try to apply the manual permissions migration, I keep getting the issue below. I assume it has something to do with the structure of where my models live.

Project structure:
```
   my_app/
    manage.py
    config/
        __init__.py
        settings.py
        urls.py
        wsgi.py
    core/
        migrations/
            __init__.py
        models/
            __init__.py
            users.py
            company.py
            <other model>.py
            <other model>.py
        __init__.py
        admin.py
        apps.py
        models.py
        tests.py
        views.py
```

Error:
```
File "/usr/local/lib/python3.8/site-packages/django/apps/config.py", line 178, in get_model
    return self.models[model_name.lower()]
KeyError: 'organization'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    main()
  File "./manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 85, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 243, in handle
    post_migrate_state = executor.migrate(
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 227, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/operations/special.py", line 190, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/usr/local/lib/python3.8/site-packages/openwisp_users/migrations/__init__.py", line 15, in set_default_organization_uuid
    organization = apps.get_model(model_app_label, 'organization')
  File "/usr/local/lib/python3.8/site-packages/django/apps/registry.py", line 211, in get_model
    return app_config.get_model(model_name, require_ready=require_ready)
  File "/usr/local/lib/python3.8/site-packages/django/apps/config.py", line 180, in get_model
    raise LookupError(
LookupError: App 'core' doesn't have a 'organization' model.
```
