### ISSUE TITLE
Integration test breaking for 'test_login_page`

### ISSUE THREAD

**Issue by devkapilbansal** [openwisp/openwisp-users#213]
`test_login_page` in `test_admin.py` is failing integration tests in other modules.

https://github.com/openwisp/openwisp-users/blob/e3577f03a0c381e1ab53ace751dd902d3498647d/openwisp_users/tests/test_admin.py#L1482-L1494

<details>
<summary>Failing test </summary>

```
======================================================================
FAIL: test_login_page (openwisp2.sample_radius.tests.TestUsersIntegration) [Test forgot password link]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kapil/Development/OPENWISP/openwisp-radius/venv/lib/python3.8/site-packages/openwisp_users/tests/test_admin.py", line 1486, in test_login_page
    self.assertContains(
  File "/home/kapil/Development/OPENWISP/openwisp-radius/venv/lib/python3.8/site-packages/django/test/testcases.py", line 470, in assertContains
    self.assertTrue(real_count != 0, msg_prefix + "Couldn't find %s in response" % text_repr)
AssertionError: False is not true : Couldn't find '<a href="/accounts/password/reset/">Forgot Password?</a>' in response

======================================================================
FAIL: test_login_page (openwisp2.sample_radius.tests.TestUsersIntegration) [Test username label]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kapil/Development/OPENWISP/openwisp-radius/venv/lib/python3.8/site-packages/openwisp_users/tests/test_admin.py", line 1492, in test_login_page
    self.assertContains(r, 'Email, phone number or username:')
  File "/home/kapil/Development/OPENWISP/openwisp-radius/venv/lib/python3.8/site-packages/django/test/testcases.py", line 470, in assertContains
    self.assertTrue(real_count != 0, msg_prefix + "Couldn't find %s in response" % text_repr)
AssertionError: False is not true : Couldn't find 'Email, phone number or username:' in response

======================================================================
FAIL: test_login_page (openwisp2.sample_users.tests.TestBasicUsersIntegration) [Test forgot password link]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kapil/Development/OPENWISP/openwisp-radius/venv/lib/python3.8/site-packages/openwisp_users/tests/test_admin.py", line 1486, in test_login_page
    self.assertContains(
  File "/home/kapil/Development/OPENWISP/openwisp-radius/venv/lib/python3.8/site-packages/django/test/testcases.py", line 470, in assertContains
    self.assertTrue(real_count != 0, msg_prefix + "Couldn't find %s in response" % text_repr)
AssertionError: False is not true : Couldn't find '<a href="/accounts/password/reset/">Forgot Password?</a>' in response

======================================================================
FAIL: test_login_page (openwisp2.sample_users.tests.TestBasicUsersIntegration) [Test username label]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kapil/Development/OPENWISP/openwisp-radius/venv/lib/python3.8/site-packages/openwisp_users/tests/test_admin.py", line 1492, in test_login_page
    self.assertContains(r, 'Email, phone number or username:')
  File "/home/kapil/Development/OPENWISP/openwisp-radius/venv/lib/python3.8/site-packages/django/test/testcases.py", line 470, in assertContains
    self.assertTrue(real_count != 0, msg_prefix + "Couldn't find %s in response" % text_repr)
AssertionError: False is not true : Couldn't find 'Email, phone number or username:' in response
```
</details>

**Comment by nemesisdesign** [comment]
Not a bug, it's a bug in the sample apps of the other modules which needs to be fixed.
