### ISSUE TITLE
[bug] REST API errors while opening API Docs

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-users#291]
Follow up of https://github.com/openwisp/openwisp-users/pull/264.

Errors like the following appear in the development server output when opening the browser to: http://localhost:8000/api/v1/docs/

```
Traceback (most recent call last):
  File "/.virtualenvs/openwisp2/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2336, in to_python
    return uuid.UUID(**{input_form: value})
  File "/usr/lib/python3.8/uuid.py", line 168, in __init__
    hex = hex.replace('urn:', '').replace('uuid:', '')
AttributeError: 'AnonymousUser' object has no attribute 'replace'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/.virtualenvs/openwisp2/lib/python3.8/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/code/openwisp/openwisp-users/openwisp_users/api/views.py", line 101, in get_queryset
    org_users = OrganizationUser.objects.filter(user=user).select_related(
  File "/.virtualenvs/openwisp2/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/.virtualenvs/openwisp2/lib/python3.8/site-packages/django/db/models/query.py", line 942, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/.virtualenvs/openwisp2/lib/python3.8/site-packages/django/db/models/query.py", line 962, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, *args, **kwargs)
  File "/.virtualenvs/openwisp2/lib/python3.8/site-packages/django/db/models/query.py", line 969, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/.virtualenvs/openwisp2/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1358, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/.virtualenvs/openwisp2/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/.virtualenvs/openwisp2/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1319, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/.virtualenvs/openwisp2/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1165, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/.virtualenvs/openwisp2/lib/python3.8/site-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/.virtualenvs/openwisp2/lib/python3.8/site-packages/django/db/models/fields/related_lookups.py", line 117, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/.virtualenvs/openwisp2/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2320, in get_prep_value
    return self.to_python(value)
  File "/.virtualenvs/openwisp2/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 2338, in to_python
    raise exceptions.ValidationError(
django.core.exceptions.ValidationError: ['“AnonymousUser” is not a valid UUID.']
view's TemplateDetailView raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/.virtualenvs/openwisp2/lib/python3.8/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/code/openwisp/openwisp-users/openwisp_users/api/mixins.py", line 33, in get_queryset
    return self.get_organization_queryset(qs)
  File "/code/openwisp/openwisp-users/openwisp_users/api/mixins.py", line 37, in get_organization_queryset
    **{self.organization_lookup: getattr(self.request.user, self._user_attr)}
AttributeError: 'AnonymousUser' object has no attribute 'organizations_managed'
view's LibraryDetailView raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/.virtualenvs/openwisp2/lib/python3.8/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/code/openwisp/openwisp-users/openwisp_users/api/mixins.py", line 33, in get_queryset
    return self.get_organization_queryset(qs)
  File "/code/openwisp/openwisp-users/openwisp_users/api/mixins.py", line 37, in get_organization_queryset
    **{self.organization_lookup: getattr(self.request.user, self._user_attr)}
AttributeError: 'AnonymousUser' object has no attribute 'organizations_managed'
view's BookNestedShelfListCreateView raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/.virtualenvs/openwisp2/lib/python3.8/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File "/.virtualenvs/openwisp2/lib/python3.8/site-packages/rest_framework/generics.py", line 110, in get_serializer
    return serializer_class(*args, **kwargs)
  File "/code/openwisp/openwisp-users/openwisp_users/api/mixins.py", line 163, in __init__
    self.filter_fields()
  File "/code/openwisp/openwisp-users/openwisp_users/api/mixins.py", line 139, in filter_fields
    organization_filter = getattr(user, self._user_attr)
AttributeError: 'AnonymousUser' object has no attribute 'organizations_managed'
```

**Comment by aagman945** [comment]
Hey I think this is because of
`if app_settings.API_DOCS:
    schema_view = get_schema_view(
        openapi.Info(**app_settings.API_INFO),
        public=True,
        permission_classes=(
            permissions.AllowAny if settings.DEBUG else permissions.IsAuthenticated,
        ),
    )`
in openwisp_utils/api./urls.py , if `DEBUG=False`, then this error won't occur.
